backend:
  name: git-gateway
  repo: mendbayare/epa-lab
  branch: main

media_folder: static/images
public_folder: /images

collections:
  - name: posts
    label: "Мэдээ / News"
    folder: content/mn/news
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Гарчиг / Title", name: "title", widget: "string" }
      - { label: "Огноо / Date", name: "date", widget: "datetime" }
      - { label: "Агуулга / Body", name: "body", widget: "markdown" }
      - { label: "Таг / Tags", name: "tags", widget: "list", required: false }

  - name: posts_en
    label: "News (English)"
    folder: content/en/news
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", required: false }

  - name: members
    label: "Гишүүд / Members"
    folder: content/mn/members
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Нэр / Name", name: "title", widget: "string" }
      - { label: "Албан тушаал / Title", name: "params_title", widget: "string" }
      - { label: "Зураг / Photo", name: "params_photo", widget: "image" }
      - { label: "Он / Year", name: "params_year", widget: "number", value_type: "int" }
      - { label: "Амжилт / Achievements", name: "params_achievements", widget: "list", required: false }
      - { label: "Дэлгэрэнгүй / Body", name: "body", widget: "markdown", required: false }

  - name: members_en
    label: "Members (English)"
    folder: content/en/members
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Title/Position", name: "params_title", widget: "string" }
      - { label: "Photo", name: "params_photo", widget: "image" }
      - { label: "Year", name: "params_year", widget: "number", value_type: "int" }
      - { label: "Achievements", name: "params_achievements", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }

  - name: research
    label: "Судалгаа / Research"
    folder: content/mn/research
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Гарчиг / Title", name: "title", widget: "string" }
      - { label: "Тайлбар / Description", name: "description", widget: "markdown" }

  - name: research_en
    label: "Research (English)"
    folder: content/en/research
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }

